version: "3.3"
services:
  destructinator:
    restart: always
    build: ./DESTRUCTINATOR/dist/deploy
    ports:
      - "1169:8080"
    logging:
        driver: "json-file"
        options:
            max-file: "3"
            max-size: 10m
  
  reject_humanity:
    restart: always
    build: ./reject_humanity_return_to_libc/dist/deploy
    ports:
      - "7979:8080"
    logging:
        driver: "json-file"
        options:
            max-file: "3"
            max-size: 10m

  unlock_door:
    restart: always
    build: ./UNLOCK_DOOR/dist/deploy
    ports:
      - "3090:8080"
    logging:
        driver: "json-file"
        options:
            max-file: "3"
            max-size: 10m

  pirates_2:
    restart: always
    build: ../forensics/pirates_2/dist/deploy
    ports:
      - "6009:5000"
    logging:
        driver: "json-file"
        options:
            max-file: "3"
            max-size: 10m
