version: "3.3"
services:
  curly_fries_1:
    restart: always
    build: ./curly_fries_1/src
    ports:
      - "8880:5000"
    logging:
        driver: "json-file"
        options:
            max-file: "3"
            max-size: 10m
  
  curly_fries_2:
    restart: always
    build: ./curly_fries_2/src
    ports:
      - "2052:5000"
    logging:
        driver: "json-file"
        options:
            max-file: "3"
            max-size: 10m

  heres_a_flag:
    restart: always
    build: ./heres_a_flag/src
    ports:
      - "2086:80"
    logging:
        driver: "json-file"
        options:
            max-file: "3"
            max-size: 10m

  hungry_man:
    restart: always
    build: ./hungry_man/hungryman
    ports:
      - "2095:5000"
    logging:
        driver: "json-file"
        options:
            max-file: "3"
            max-size: 10m

  mega_mailer:
    restart: always
    build: ./mega_mailer/dist/deploy
    ports:
      - "8080:5000"
    logging:
        driver: "json-file"
        options:
            max-file: "3"
            max-size: 10m
